/**
 * @fileoverview Drizzle ORM schema for Saksham mental wellness app.
 * Defines all database tables with proper types and timestamps.
 * Uses anonymous userId (session ID) — no PII stored.
 *
 * AUTH BOUNDARY:
 * userId is an opaque anonymous session ID stored in an httpOnly cookie.
 * No email, name, or identifying information is stored in the DB.
 * The session cookie is the sole identity token.
 */
import {
  pgTable,
  text,
  integer,
  timestamp,
  real,
  varchar,
  json,
} from 'drizzle-orm/pg-core';
import { nanoid } from 'nanoid';

/** Journal entries written by users */
export const journalEntries = pgTable('journal_entries', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => nanoid()),
  userId: text('user_id').notNull(),
  content: text('content').notNull(),
  moodScore: integer('mood_score').notNull(), // 1–5
  aiReflection: text('ai_reflection'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/** Quick mood check-ins (separate from journal) */
export const moodLogs = pgTable('mood_logs', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => nanoid()),
  userId: text('user_id').notNull(),
  score: integer('score').notNull(), // 1–5
  emoji: text('emoji').notNull(),
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/**
 * Detected stress triggers from insight engine analysis.
 * Populated automatically when journal entries are analyzed.
 */
export const stressTriggers = pgTable('stress_triggers', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => nanoid()),
  userId: text('user_id').notNull(),
  trigger: varchar('trigger', { length: 100 }).notNull(), // e.g., 'exam_dates', 'peer_comparison'
  category: varchar('category', { length: 50 }).notNull(),
  frequency: integer('frequency').notNull().default(1),
  confidenceScore: real('confidence_score').notNull(), // 0–1
  lastSeen: timestamp('last_seen', { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/**
 * Emotional patterns detected over time (e.g., declining mood trend).
 * Generated by detectPatterns() pure function.
 */
export const emotionalPatterns = pgTable('emotional_patterns', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => nanoid()),
  userId: text('user_id').notNull(),
  patternType: varchar('pattern_type', { length: 100 }).notNull(), // e.g., 'declining_mood', 'weekend_slump'
  severity: varchar('severity', { length: 20 }).notNull(), // 'mild', 'moderate', 'severe'
  description: text('description').notNull(),
  metadata: json('metadata').$type<Record<string, unknown>>(),
  detectedAt: timestamp('detected_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/** Completed mindfulness exercises */
export const wellnessCheckins = pgTable('wellness_checkins', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => nanoid()),
  userId: text('user_id').notNull(),
  exercise: varchar('exercise', { length: 100 }).notNull(), // e.g., 'box_breathing', 'grounding_5-4-3-2-1'
  duration: integer('duration').notNull(), // seconds
  moodBefore: integer('mood_before'),
  moodAfter: integer('mood_after'),
  completedAt: timestamp('completed_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

// TypeScript types inferred from schema
export type JournalEntry = typeof journalEntries.$inferSelect;
export type NewJournalEntry = typeof journalEntries.$inferInsert;
export type MoodLog = typeof moodLogs.$inferSelect;
export type NewMoodLog = typeof moodLogs.$inferInsert;
export type StressTrigger = typeof stressTriggers.$inferSelect;
export type NewStressTrigger = typeof stressTriggers.$inferInsert;
export type EmotionalPattern = typeof emotionalPatterns.$inferSelect;
export type NewEmotionalPattern = typeof emotionalPatterns.$inferInsert;
export type WellnessCheckin = typeof wellnessCheckins.$inferSelect;
export type NewWellnessCheckin = typeof wellnessCheckins.$inferInsert;
